title: O Reino da Computação
description: >- # this means to ignore newlines until "baseurl:"
  Blog pessoal de Renato Monteiro Batista, engenheiro de computação. Um espaço para compartilhar conhecimento, experiências e descobertas sobre sistemas, redes, software livre, segurança, inteligência artificial e computação em geral.
url: "https://renatomb.github.io"
twitter_username: renatomb
github_username:  renatomb
gtag: G-HQ5W1JT80C

theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-sitemap